name: Docker CI/CD

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce
        sudo usermod -aG docker $USER

    - name: Start MySQL Container
      run: |
        docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=fatan12345 -e MYSQL_DATABASE=learning mysql:latest

    - name: Start Redis Container
      run: |
        docker run -d --name redis redis:latest

    - name: Build Docker Image
      run: |
        docker build -t golang-redis:${{ github.sha }} .
        docker tag golang-redis:${{ github.sha }} golang-redis:latest
      working-directory: ./docker/build.sh
      

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker push golang-redis:${{ github.sha }}
        docker push golang-redis:latest

    - name: Stop Containers
      run: |
        docker stop mysql
        docker rm mysql
        docker stop redis
        docker rm redis
